// Build step. Generates the three files that depend on the environment:
//
//   web/js/config.js   — carries the ImgBB key
//   web/sitemap.xml    — needs absolute URLs
//   web/robots.txt     — needs an absolute sitemap URL
//
// All three are gitignored, so the API key never enters the repository and
// no deployment URL is hardcoded anywhere. Run it locally with `node
// scripts/build.js`; Vercel runs it automatically via buildCommand.
//
// Dependency-free on purpose: no package.json, no install step, so the
// whole site stays a plain static deploy.

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const WEB = path.join(ROOT, "web");

// ---- Environment -----------------------------------------------------------

// Minimal .env reader. Vercel injects real environment variables, so this is
// only used for local development.
function loadDotEnv() {
  const file = path.join(ROOT, ".env");
  if (!fs.existsSync(file)) return;
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    // Real environment variables always win over the file.
    if (process.env[key] === undefined) process.env[key] = val;
  }
}
loadDotEnv();

// Vercel sets VERCEL_PROJECT_PRODUCTION_URL to the stable production domain
// and VERCEL_URL to the per-deployment one. Prefer the stable domain so
// preview builds don't emit canonicals pointing at a throwaway URL.
function siteUrl() {
  const explicit = (process.env.SITE_URL || "").trim();
  if (explicit) return explicit.replace(/\/+$/, "");

  const prod = (process.env.VERCEL_PROJECT_PRODUCTION_URL || "").trim();
  if (prod) return "https://" + prod.replace(/\/+$/, "");

  const deploy = (process.env.VERCEL_URL || "").trim();
  if (deploy) return "https://" + deploy.replace(/\/+$/, "");

  return "http://localhost:4173"; // local development
}

const SITE = siteUrl();
const KEY = (process.env.IMGBB_KEY || "").trim();
const EXPIRY = (process.env.IMGBB_EXPIRY_SECONDS || "").trim();

// ---- web/js/config.js ------------------------------------------------------

const expiryLiteral = EXPIRY && !isNaN(Number(EXPIRY)) ? Number(EXPIRY) : null;

fs.writeFileSync(
  path.join(WEB, "js", "config.js"),
  `// GENERATED by scripts/build.js — do not edit, and do not commit.
// Values come from environment variables (.env locally, Project Settings on
// Vercel). This file is gitignored so the key stays out of the repository.
//
// It is still served to every visitor, so it is readable by anyone who views
// source. Keeping it out of git prevents automated scraping of the public
// repo; it does not make the key secret at runtime. Only a server-side proxy
// could do that. Use a key created solely for this site and rotate it freely.
window.QodeConfig = {
  imgbbKey: ${JSON.stringify(KEY)},
  imgbbExpirySeconds: ${expiryLiteral === null ? "null" : expiryLiteral},
};
`,
  "utf8"
);

// ---- web/sitemap.xml -------------------------------------------------------

const PAGES = [
  { loc: "/", changefreq: "weekly", priority: "1.0" },
  { loc: "/wizard", changefreq: "monthly", priority: "0.8" },
  { loc: "/switch", changefreq: "monthly", priority: "0.8" },
  { loc: "/bulk", changefreq: "monthly", priority: "0.8" },
];

fs.writeFileSync(
  path.join(WEB, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PAGES.map(
  (p) => `  <url>
    <loc>${SITE}${p.loc}</loc>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`
).join("\n")}
</urlset>
`,
  "utf8"
);

// ---- web/robots.txt --------------------------------------------------------

fs.writeFileSync(
  path.join(WEB, "robots.txt"),
  `User-agent: *
Allow: /

# The redirect interstitial carries no content of its own and its target
# lives in a URL fragment that crawlers never see.
Disallow: /r

Sitemap: ${SITE}/sitemap.xml
`,
  "utf8"
);

// ---- og:image URLs in the HTML ---------------------------------------------

// og:image has to be absolute — crawlers do not reliably resolve a relative
// one — but the deploy domain isn't known until this runs. So the committed
// HTML carries a __SITE__ placeholder and it is substituted here.
//
// Deliberately skipped when falling back to localhost: otherwise a local
// build would rewrite the committed HTML with a localhost URL, and that would
// eventually get committed. Nothing scrapes localhost, so leaving the
// placeholder in place there is harmless.
const isRealDeploy = !SITE.startsWith("http://localhost");

if (isRealDeploy) {
  let patched = 0;
  for (const page of ["index.html", "wizard.html", "bulk.html"]) {
    const file = path.join(WEB, page);
    if (!fs.existsSync(file)) continue;
    const before = fs.readFileSync(file, "utf8");
    const after = before.split("__SITE__").join(SITE);
    if (after !== before) {
      fs.writeFileSync(file, after, "utf8");
      patched++;
    }
  }
  console.log("build: og:image URLs written into " + patched + " page(s)");
} else {
  console.log("build: local build — leaving __SITE__ placeholders in the HTML");
}

// ---- Report ----------------------------------------------------------------

console.log("build: site URL   " + SITE);
console.log("build: imgbb key  " + (KEY ? "set (" + KEY.length + " chars)" : "MISSING — the Image type will not work"));
console.log("build: wrote web/js/config.js, web/sitemap.xml, web/robots.txt");

if (!KEY) {
  console.warn("\n  WARNING: IMGBB_KEY is empty. Every other content type still works;\n  only the Image type needs it. Set it in Vercel -> Project Settings ->\n  Environment Variables, then redeploy.\n");
}
